### ISSUE TITLE
global: removal of Flask-CLI

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-memento#7]

**Comment by cg-cnu** [comment]
First time open source contributor here... 
Forked the repo, made the changes and commited here.... https://github.com/cg-cnu/invenio-memento/tree/remove-flask-cli-dep

Running the tests gave this error... 

Warning, treated as error:

```
/home/salapati/codemonk/invenio-memento/docs/usage.rst:28: WARNING: autodoc: failed to import module u'invenio_memento'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/sphinx/ext/autodoc.py", line 519, in import_object
    __import__(self.modname)
ImportError: No module named invenio_memento 

I think I can fix this but need little bit of help.
Thanks.
```

**Comment by jirikuncar** [comment]
@cg-cnu try to install the package with all dependencies before running tests `pip install -e .[all]` (or `pip install -e .[docs,tests]`).
